apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: vm-alert-custom-rules-k8s-test.rules
  namespace: vm
  labels:
    app: victoria-metrics-k8s-stack
    app.kubernetes.io/name: victoria-metrics-k8s-stack
spec:
  groups:
  - name: custom-rules-k8s-test.rules
    #interval: 15s
    rules:

    # 占位
    - record: rule:vm-alert-custom-rules-k8s-test
      expr  : "1"

    # # 报警：pod Pending 时间过长
    # - alert: discoverd_custom_alert
    #   expr: kube_pod_status_phase{namespace=~"harbor|vm",phase="Pending",pod="loki-backend-0"} + 1 == 1
    #   for : 2m
    #   labels:
    #     severity: critical
    #     retitle : bz1-shenshu1 - pod Pending 时间过长
    #     rename  : disable
    #     test    : "1"
    #     mentioned_list: "ou_acd0ea6e87d242d3713b3381ad5d6523"
    #   annotations:
    #     summary: "命名空间: {{ $labels.namespace }} | pod: {{ $labels.pod }} | 状态: {{ $labels.phase }}"
    #     mentioned_list: "ou_acd0ea6e87d242d3713b3381ad5d6523" # 杨海涛

    # # 报警：pod 状态异常
    # - alert: discoverd_custom_alert
    #   expr: (kube_pod_status_phase{phase!~"Running|Pending|Succeeded"} > 0) and on (pod, namespace) (time() - kube_pod_start_time) > 300
    #   for : 2m
    #   labels:
    #     severity: critical
    #     retitle : bz1-shenshu1 - pod 状态异常
    #     rename  : disable
    #     test    : "1"
    #   annotations:
    #     summary: "命名空间: {{ $labels.namespace }} | pod: {{ $labels.pod }} | 状态: {{ $labels.phase }}"

    # # 报警：pod container 状态异常
    # - alert: discoverd_custom_alert
    #   expr: kube_pod_container_status_waiting_reason == 1 
    #   for : 2m
    #   labels:
    #     severity: critical
    #     retitle : bz1-shenshu1 - pod container 状态异常
    #     rename  : disable
    #     test    : "1"
    #   annotations:
    #     summary: "命名空间: {{ $labels.namespace }} | pod: {{ $labels.pod }} | 容器: {{ $labels.container }} | 原因: {{ $labels.reason }}"

    # # 报警：pod container 持续重启
    # - alert: discoverd_custom_alert
    #   expr: kube_pod_container_status_restarts_total > 2 and (increase(kube_pod_container_status_restarts_total[6m]) > 0 or increase(kube_pod_container_status_restarts_total[6m]) offset 1m > 0 )
    #   for : 2m
    #   labels:
    #     severity: critical
    #     retitle : bz1-shenshu1 - pod container 持续重启
    #     rename  : disable
    #     test    : "1"
    #   annotations:
    #     summary: "命名空间: {{ $labels.namespace }} | pod: {{ $labels.pod }} | 容器: {{ $labels.container }} | 重启次数: {{ $value }}"
