#!/bin/bash

set -e

dir=$(cd "$(dirname "$0")"; pwd)

cd $dir/charts

helm repo add vm https://victoriametrics.github.io/helm-charts/
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm repo update vm
helm repo update prometheus-community

helm pull vm/victoria-metrics-k8s-stack
helm pull prometheus-community/prometheus-operator-crds
