prometheus-blackbox-exporter:
  enabled: false

  # serviceMonitor:
  #   enabled: true

  #   targets:
  #   - name: pypi                    # Human readable URL that will appear in Prometheus / AlertManager
  #     url: https://pypi.hs1.paratera.com # The URL that blackbox will scrape
  #     hostname: pypi.hs1.paratera.com            # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
  #     labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
  #     interval: 60s                    # Scraping interval. Overrides value set in `defaults`
  #     scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
  #     module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
  #     additionalMetricsRelabels: {}    # Map of metric labels and values to add
  #     additionalRelabeling: []         # List of metric relabeling actions to run


x509-certificate-exporter:
  enabled: true

  secretsExporter:
    enabled: true

    # -- Which type of Secrets should be watched ; "key" is the map key in the secret data
    # @default -- check `values.yaml`
    secretTypes:
    - type: kubernetes.io/tls
      key: tls.crt
    - type: Opaque
      key: tls.crt

  # 是否创建 service，若 secretsExporter.enabled 为 false，则此项应为 true
  service:
    create: true
  
  # 是否创建 serviceMonitor，开启后，prometheus 或 vm 可以接入数据
  prometheusServiceMonitor:
    create: true
  
  prometheusPodMonitor:
    create: false

  prometheusRules:
    create: false
