apiVersion: v1
kind: Service
metadata:
  name: node-exporter-prom-scrape
  namespace: mon
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP