apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gpu
spec:
  rules:
    - name: "RTX 4090"
      labels:
        "node-role.kubernetes.io/gpu": "true"
        "nvidia.com/gpu": "rtx-4090"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["10de"] }
            device: { op: In, value: ["2684"] }
        - feature: system.name
          matchExpressions:
            nodename: { op: InRegexp, value: ["^gn"] }
    - name: "RTX 5090"
      labels:
        "node-role.kubernetes.io/gpu": "true"
        "nvidia.com/gpu": "rtx-5090"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["10de"] }
            device: { op: In, value: ["2b85"] }
        - feature: system.name
          matchExpressions:
            nodename: { op: InRegexp, value: ["^gn"] }