apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-tests-single-node-gn001
  # namespace: mpi-operator
spec:
  slotsPerWorker: 8
  launcherCreationPolicy: WaitForWorkersReady
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - gn001
          containers:
            - image: cr.hs1h-int.paratera.com/tests/nccl-tests:12.8.1-devel-ubuntu22.04-nccl2.27.7-1-2c1d5fe
              imagePullPolicy: Always
              name: nccl
              env:
                - name: OMPI_ALLOW_RUN_AS_ROOT
                  value: "1"
                - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
                  value: "1"
              # command: ["sleep", "infinity"]
              command: ["/bin/bash", "-c"]
              args: [
                  "mpirun \
                  -np 8 \
                  -bind-to none \
                  /opt/nccl_tests/build/alltoall_perf -b 1g -e 1G -f 2 -g 1 \
                  ",
                ]
                  # -x LD_LIBRARY_PATH \
                  # -x NCCL_SOCKET_IFNAME=eth0 \
                  # -x NCCL_IB_HCA=mlx5 \
                  # -x NCCL_ALGO=Ring \
                  # -x NCCL_IB_QPS_PER_CONNECTION=4 \
                  # -x NCCL_CROSS_NIC=1 \
                  # -x UCX_NET_DEVICES=all \
                  # -x NCCL_NET=UCX \
                  # -x UCX_TLS=all \
                  # -x NCCL_DEBUG=INFO \
                  # -x NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH \
                  # -x NCCL_ALGO=Ring \
                  # -x NCCL_IB_QPS_PER_CONNECTION=4 \
                  # -x NCCL_CROSS_NIC=1 \
              resources:
                requests:
                  cpu: 2
                  memory: 128Mi
          tolerations:
            - operator: Exists
              effect: NoSchedule
          enableServiceLinks: false
          automountServiceAccountToken: false
    Worker:
      replicas: 1
      template:
        metadata:
          labels:
            job: nccl-test
          # annotations:
          #   k8s.v1.cni.cncf.io/networks: default/rdma-net-ipam
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - gn001
          containers:
            - image: cr.hs1h-int.paratera.com/tests/nccl-tests:12.8.1-devel-ubuntu22.04-nccl2.27.7-1-2c1d5fe
              imagePullPolicy: Always
              name: nccl
              resources:
                limits:
                  cpu: 80
                  memory: 100Gi
                  nvidia.com/gpu: 8
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              securityContext:
                capabilities: 
                  add: 
                    - IPC_LOCK
          volumes:
            - emptyDir:
                medium: Memory
              name: dshm
          tolerations:
            - operator: Exists
              effect: NoSchedule
          enableServiceLinks: false
          automountServiceAccountToken: false
