nfd:
  enabled: false

daemonsets:
  tolerations:
    - operator: Exists
      effect: NoSchedule 

operator:
  resources:
    limits:
      cpu: null
      memory: 2Gi
  tolerations:
    - operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists

driver:
  enabled: false
  version: "570.148.08"
  env:
  # - name: http_proxy
  #   value: http://10.29.1.201:3128
  # - name: https_proxy
  #   value: http://10.29.1.201:3128
  # - name: no_proxy
  #   value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,100.64.0.0/10,localhost,*.local,*.bj8.zz2.paratera.com,*.bj8.zz2.blsc.cn"
  kernelModuleType: proprietary
  rdma:
    enabled: false
    useHostMofed: false
  repoConfig:
    configMapName: repo-config
  # close GPU GSP (optional)
  kernelModuleConfig:
    name: "kernel-module-params"

toolkit:
  env:
    ## env for k3s
    # - name: CONTAINERD_CONFIG
    #   value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    # - name: CONTAINERD_SOCKET
    #   value: /run/k3s/containerd/containerd.sock
    # - name: CONTAINERD_RUNTIME_CLASS
    #   value: nvidia
    # - name: CONTAINERD_SET_AS_DEFAULT
    #   value: "true"
    # - name: NVIDIA_CONTAINER_RUNTIME_LOG_LEVEL
    #   value: "warning"
    ## env for k8s
    - name: CONTAINERD_CONFIG
      value: /etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"

dcgmExporter:
  args:
    - --collect-interval
    - "1000"
  enabled: true
  env:
    - name: DCGM_EXPORTER_LISTEN
      value: ":9400"
    - name: DCGM_EXPORTER_KUBERNETES
      value: "true"
  repository: cr.zw1.paratera.com/ids
  image: dcgm-exporter
  version: 4.2.3-4.1.3-ubuntu22.04-ids
  config:
    name: dcgm-exporter-config

migManager:
  enabled: true