apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guopf
  namespace: gpu-operator
rules:
- apiGroups:
    - "*"
  resources:
    - "pods"
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guopf
  namespace: gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guopf
subjects:
  - kind: ServiceAccount
    name: guopf
    namespace: sa-management