{{- if and .Values.webConfiguration (not .Values.webConfigurationExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x509-certificate-exporter.webConfigurationSecretName" . }}
  namespace: {{ include "x509-certificate-exporter.namespace" . }}
  labels:
    {{- include "x509-certificate-exporter.labels" . | nindent 4 }}
data:
    webconfig.yaml: {{ .Values.webConfiguration | b64enc | quote }}
{{- end }}
