apiVersion: v1
kind: ServiceAccount
metadata:
  name: mon-ids-qos-alert-adaptor
  namespace: mon  # 通常放在 kube-system 命名空间
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mon-ids-node-manager-role
rules:
  # 节点相关权限（cordon/uncordon + taint）
  - apiGroups: [""]  # 空表示核心 API 组
    resources: ["nodes"]  # 节点资源
    verbs: ["get", "list", "patch", "update"]  # cordon 和 uncordon 所需的权限
  # Pod 删除权限
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  # Pod 驱逐权限（使用 eviction API）
  - apiGroups: ["policy"]
    resources: ["pods/eviction"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mon-node-manager-binding
roleRef:
  kind: ClusterRole
  name: mon-ids-node-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: mon-ids-qos-alert-adaptor
  namespace: mon  # 与 ServiceAccount 的命名空间一致